# Generated by Django 3.0.5 on 2023-08-21 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auctionitem_txid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='image',
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=228, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
