# Generated by Django 3.0.5 on 2023-08-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20230821_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='auctionBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidderUser', models.CharField(max_length=100, null=True)),
                ('bidAmount', models.FloatField()),
                ('auction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auction.auctionItem')),
            ],
        ),
    ]
