# Generated by Django 4.2.4 on 2023-08-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0005_auctionitem_bidwinner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionitem",
            name="bidWinner",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name="auctionBid",
        ),
    ]
